Vagrant.configure(2) do |config|
  config.vm.define "lwp.vagrant", primary: true, autostart: true do |config_machine|
      #Assigning a provider
      config_machine.vm.provider :virtualbox do |virtualbox, override|
          virtualbox.name = "lxc-webpanel"
		  #override.vm.box = "chef/centos-7.0"
		  override.vm.box = "ubuntu/trusty64"
          
		  # Configuring network
          override.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
          override.vm.network :private_network, ip: "192.168.33.111"
          #override.ssh.forward_agent=true 

      end

      # Asinging a provisioner
      config_machine.vm.provision :ansible, run: "always" do |provisioner|
          provisioner.playbook = "playbook.yml"
          provisioner.extra_vars = "custom_vars.yml" if File.file?("custom_vars.yml")
          #provisioner.inventory_path= "inventory"
          provisioner.host_key_checking = false
          provisioner.verbose = "v"

          # needed if ssh client is older
	  #provisioner.extra_vars = { 
          #                 ansible_connection: 'paramiko'
	  		   }
      end
  end
end
